;2.1 显示Sample.txt
.MODEL SMALL
.STACK 1024

.DATA
    FILENAME DB 'D:\SOFTWARE\emu8086\emu8086\MyBuild\Sample.txt',0
    FILEHANDLE DW ?
    FILEHI DW ?
    FILELO DW ?
    BUFFSIZE DW ?
    BUFFER DB 2048 DUP(0)

.CODE
START:
    CALL PREADFILE          ;把文件内容读到buffer
    JMP PRINTFILE
    
PREADFILE PROC NEAR
;OPEN FILE:OPEN FILE NAMED "FILENAME"
FOPEN:
    mov AX,@DATA
    mov DS,AX
    MOV DX,OFFSET FILENAME  ;OPEN FILE
    MOV AX,3D00H              ;CONTROL
    INT 21H                 ;OPEN FILE
    MOV FILEHANDLE,AX

;COUNT THE SIZE OF FILE
SIZECOUNT:
    CALL MOVFHH
    MOV FILEHI,DX
    MOV FILELO,AX
    CALL MOVFHT
    SUB DX,FILEHI
    MOV FILEHI,DX
    SUB AX,FILELO
    MOV FILELO,AX
    MOV BUFFSIZE,AX
    JMP READFILE
        
;MOVE FILE HANDLE TO HEAD OF FILE
MOVFHH:
    MOV AH,42H
    MOV BX,FILEHANDLE
    MOV AL,0
    MOV CX,0
    MOV DX,0
    INT 21H
    RET

;MOVE FILE HANDLE TO TAIL OF FILE
MOVFHT:
    MOV AH,42H
    MOV BX,FILEHANDLE
    MOV AL,2
    MOV CX,0
    MOV DX,0
    INT 21H
    RET        
 
;READ FILE:COPY NUMBERS INTO ARRAY[]
READFILE:
    CALL MOVFHH
    MOV AH,3FH
    MOV BX,FILEHANDLE
    MOV DX,OFFSET BUFFER
    MOV CX,BUFFSIZE
    INT 21H
    
;CLOSE FILE
CLOSEF:
    MOV AH,3EH
    MOV BX,FILEHANDLE
    INT 21H

ENDOFREADFILE:
    RET
               
PREADFILE ENDP

;显示文件内容
PRINTFILE: 
    LEA DI,BUFFER
    
PLOOP:
    MOV DL,[DI]
    CMP DL,0          ;结束符是'\0'
    JZ LEAVE
    MOV AH,02H
    INT 21H
    ADD DI,1
    JMP PLOOP

;结束
LEAVE:
    MOV AH,4CH
    INT 21H