;把BUFFER中的字节转换成数字存储到ARRAY
;格式是 141 855 以空格为结束？
;支持十进制
;需要提前定义：
;BUFFSIZE DW ?
;BUFFER DB 2048 DUP(0)
;N DW 0
;TEMP DW 0      
;ARRAY DB 1024 DUP(0)
;TEN DB 10

.DATA
    BUFFSIZE DW ?
    BUFFER DB 2048 DUP(0)
    N DW 0
    TEMP DW 0      
    ARRAY DB 1024 DUP(0)
    TEN DB 10

.CODE
STRINGTONUM PROC NEAR
;READ NUM FROM BUFFER TO ARRAY[]    
READNUM:
    XOR AX,AX
    MOV CX,1    ;COUNT BUFFER
    MOV BX,0    ;COUNT ARRAY
    MOV SI,OFFSET BUFFER
    MOV DI,OFFSET ARRAY
    MOV AL,[SI]
    ADD SI,1
    SUB AL,30H
    PUSH AX
    
RLOOP:
    MOV AL,[SI]
    CMP AL,32  ;BUFFER(CX)==' '?
    JE RSPACE
    ;IS NUMBER
    POP AX         ;LAST PLACE *10
    MUL TEN
    ADD AL,[SI]
    SUB AL,30H      ;ASCII -> NUM
    PUSH AX
    ADD SI,1
    INC CX
    CMP CX,BUFFSIZE
    JZ ENDOFSTRINGTONUM        ;READ END
    JMP RLOOP  

;MEET A SPACE-> STORE A NUMBER TO ARRAY
RSPACE:
    POP AX
    MOV [DI],AL     ;ARRAY[BX]
    INC BX
    ADD DI,1
    
    XOR AX,AX       ;NEXT NUM
    ADD SI,1
    MOV AL,[SI]
    SUB AL,30H
    PUSH AX
    ADD SI,1

    ADD CX,2
    CMP CX,BUFFSIZE
    JZ ENDOFSTRINGTONUM
    JMP RLOOP

;结束
ENDOFSTRINGTONUM:
    RET
            
STRINGTONUM ENDP